### ISSUE TITLE
森くんに連絡

### ISSUE THREAD

**Issue by cojimasaori** [cojimasaori/Gallery-MUGEN#11]
Gallery への参画可否

**Comment by shimada-koki** [comment]
@TomoyoHashida @cojimasaori 
お誘いは喜んでくれていました。詳細は直接会って話しましょうとお伝えしています。
日程は、23日が難しいそうなので、
28日の夕方で打診して大丈夫かな？ともよちゃんご都合どうでしょう？

**Comment by TomoyoHashida** [comment]
@shimada-koki @cojimasaori 
調整ありがとう^^ 
28日は20時からオンライン打ち合わせが入ってるのだけど、それまでだったら全然いけるよん◎

**Comment by shimada-koki** [comment]
@TomoyoHashida 
ありがとう！では28日夕方で問いかけますー

**Comment by shimada-koki** [comment]
森くん、28日18時以降でokです。
