### ISSUE TITLE
カッティングシートのオーダー

### ISSUE THREAD

**Issue by cojimasaori** [cojimasaori/Gallery-MUGEN#26]

**Comment by shimada-koki** [comment]
【現状共有_201001】
森田に発注依頼済み。
いつまでに入稿が必要か確認中。
それ次第で、
・原稿の最終決定日
・入稿日
・納品日
が決まる。

施工は一緒に行ってくれるとのこと。

**Comment by shimada-koki** [comment]
10月7日までに森田へ入稿
